self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - linux-arm64-npu-static-8
    - linux-aarch64-310p-1
    - linux-aarch64-310p-2
    - linux-aarch64-310p-4
    - linux-aarch64-a3-1
    - linux-aarch64-a3-2
    - linux-aarch64-a3-4
    - linux-aarch64-a3-8
    - linux-aarch64-a3-0
    - linux-amd64-cpu-8-hk
    - linux-amd64-cpu-16-hk
    - linux-aarch64-a2b3-0
    - linux-aarch64-a2b3-1
    - linux-aarch64-a2b3-2
    - linux-aarch64-a2b3-4
