self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - linux-arm64-npu-1
    - linux-arm64-npu-2
    - linux-arm64-npu-4
    - linux-arm64-npu-static-8
    - ubuntu-24.04-arm
