#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
#

FROM quay.io/ascend/vllm-ascend:main-a3

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG AIS_BENCH_TAG="v3.0-20250930-master"
ARG AIS_BENCH_URL="https://gitee.com/aisbench/benchmark.git"

# Define environments
ENV DEBIAN_FRONTEND=noninteractive
ENV COMPILE_CUSTOM_KERNELS=${COMPILE_CUSTOM_KERNELS}

WORKDIR /workspace

RUN pip config set global.index-url ${PIP_INDEX_URL}

# Install requirements-dev.txt for tests
RUN export PIP_EXTRA_INDEX_URL=https://mirrors.huaweicloud.com/ascend/repos/pypi && \
    cd /vllm-workspace/vllm-ascend && \
    python3 -m pip install -r requirements-dev.txt && \
    python3 -m pip cache purge

# Install benchmark tools
RUN git clone -b ${AIS_BENCH_TAG} --depth 1 ${AIS_BENCH_URL} /vllm-workspace/vllm-ascend/benchmark && \
    cd /vllm-workspace/vllm-ascend/benchmark && \
    pip install -e . -r requirements/api.txt -r requirements/extra.txt && \
    python3 -m pip cache purge

CMD ["/bin/bash"]
