/**
 * This program is free software, you can redistribute it and/or modify it.
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef FUSED_SPARSE_ATTENTION_OVERLAP_TEMPLATE_TILING_KEY_H
#define FUSED_SPARSE_ATTENTION_OVERLAP_TEMPLATE_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND 0
#define FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND 1
#define FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_PA_BSND 2

#define ASCENDC_TPL_4_BW 4

#define C_TEMPLATE 0
#define V_TEMPLATE 1

ASCENDC_TPL_ARGS_DECL(FusedSparseAttentionOverlap,
    ASCENDC_TPL_BOOL_DECL(FLASH_DECODE, 0, 1),
    ASCENDC_TPL_UINT_DECL(LAYOUT_T, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND),
    ASCENDC_TPL_UINT_DECL(KV_LAYOUT_T, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_BSND, FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND,
        FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_PA_BSND),
    ASCENDC_TPL_UINT_DECL(TEMPLATE_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        C_TEMPLATE, V_TEMPLATE),
    ASCENDC_TPL_BOOL_DECL(IS_SPLIT_G, 0, 1),
);

// GLM-5.2 decode uses TND query layout, paged KV, the vector template, and non-split G.
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
        ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST,
            FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_TND),
        ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST,
            FUSED_SPARSE_ATTENTION_OVERLAP_LAYOUT_PA_BSND),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, V_TEMPLATE),
        ASCENDC_TPL_BOOL_SEL(IS_SPLIT_G, 0),
    ),
);

#endif // FUSED_SPARSE_ATTENTION_OVERLAP_TEMPLATE_TILING_KEY_H
