#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
#

FROM ascendai/python:3.11-ubuntu22.04

ARG TARGETARCH

RUN apt-get update -y && \
    apt-get install -y curl git gcc g++ cmake libnuma-dev jq && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/*


ARG VLLM_REPO=https://github.com/vllm-project/vllm.git
# For lint purpose, actually we need make a main2main matching.
ARG VLLM_COMMIT=9562912cead1f11e8540fb91306c5cbda66f0007
RUN git clone $VLLM_REPO /vllm-workspace/vllm && \
    cd /vllm-workspace/vllm && \
    git checkout $VLLM_COMMIT

# # Install vLLM common dependencies
RUN python3 -m pip install -r /vllm-workspace/vllm/requirements/common.txt --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y triton && \
    python3 -m pip cache purge

COPY . /vllm-workspace/vllm-ascend/

RUN pip install -r /vllm-workspace/vllm-ascend/requirements-dev.txt --extra-index-url https://download.pytorch.org/whl/cpu && \
    pip cache purge && \
    rm -fr /vllm-workspace/

CMD ["/bin/bash"]
