/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file sparse_flash_mla_template_tiling_key.h
 * \brief
 */

#ifndef SPARSE_ATTN_SHARED_TEMPLATE_TILING_KEY_H
#define SPARSE_ATTN_SHARED_TEMPLATE_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define SMLA_LAYOUT_BSND 0
#define SMLA_LAYOUT_TND 1
#define SMLA_LAYOUT_PA_BBND 2

#define ASCENDC_TPL_4_BW 4

#define SWA_TEMPLATE 0
#define HCA_TEMPLATE 1
#define CSA_TEMPLATE 2
#define ORI_SPARSE_TEMPLATE 3
#define ORI_CMP_SPARSE_TEMPLATE 4
// 模板参数支持的范围定义
ASCENDC_TPL_ARGS_DECL(SparseFlashMla, // 算子OpType
                      ASCENDC_TPL_BOOL_DECL(FLASH_DECODE, 0, 1),
                      ASCENDC_TPL_UINT_DECL(LAYOUT_T, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_BSND,
                                            SMLA_LAYOUT_TND),
                      ASCENDC_TPL_UINT_DECL(KV_LAYOUT_T, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_BSND,
                                            SMLA_LAYOUT_TND, SMLA_LAYOUT_PA_BBND),
                      ASCENDC_TPL_UINT_DECL(TEMPLATE_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, SWA_TEMPLATE,
                                            HCA_TEMPLATE, CSA_TEMPLATE, ORI_SPARSE_TEMPLATE, ORI_CMP_SPARSE_TEMPLATE),
                      ASCENDC_TPL_BOOL_DECL(SPLIT_G, 0, 1), ASCENDC_TPL_BOOL_DECL(HEAD_RATIO_ONE, 0, 1),
                      ASCENDC_TPL_BOOL_DECL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_DECL(IS_VEC_S2PHYADDR, 0, 1));

// Aurora always uses TND Q and PA_BBND KV: C0 -> SWA, C1/C2 -> CSA.
// Keep the declaration above unchanged to preserve the host/kernel key ABI.
// Only CSA on A2/A3 uses HEAD_RATIO_ONE. Split-G and vectorized sparse
// addressing belong to A5. Both deterministic levels remain reachable.
#if !defined(__CCE_AICORE__)
// Host validation accepts the union of the two device selections (14 keys).
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
                         ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_PA_BBND),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, SWA_TEMPLATE, CSA_TEMPLATE),
                         ASCENDC_TPL_BOOL_SEL(SPLIT_G, 0), ASCENDC_TPL_BOOL_SEL(HEAD_RATIO_ONE, 0),
                         ASCENDC_TPL_BOOL_SEL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_SEL(IS_VEC_S2PHYADDR, 0)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
                         ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_PA_BBND),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, CSA_TEMPLATE),
                         ASCENDC_TPL_BOOL_SEL(SPLIT_G, 0), ASCENDC_TPL_BOOL_SEL(HEAD_RATIO_ONE, 1),
                         ASCENDC_TPL_BOOL_SEL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_SEL(IS_VEC_S2PHYADDR, 0)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
                         ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_PA_BBND),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, SWA_TEMPLATE, CSA_TEMPLATE),
                         ASCENDC_TPL_BOOL_SEL(SPLIT_G, 1), ASCENDC_TPL_BOOL_SEL(HEAD_RATIO_ONE, 0),
                         ASCENDC_TPL_BOOL_SEL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_SEL(IS_VEC_S2PHYADDR, 0)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
                         ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_PA_BBND),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, CSA_TEMPLATE),
                         ASCENDC_TPL_BOOL_SEL(SPLIT_G, 0, 1), ASCENDC_TPL_BOOL_SEL(HEAD_RATIO_ONE, 0),
                         ASCENDC_TPL_BOOL_SEL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_SEL(IS_VEC_S2PHYADDR, 1)));
#elif (__CCE_AICORE__ == 310)
// A5: keep split-G and CSA vectorization; never compile HEAD_RATIO_ONE=1.
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
                         ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_PA_BBND),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, SWA_TEMPLATE),
                         ASCENDC_TPL_BOOL_SEL(SPLIT_G, 0, 1), ASCENDC_TPL_BOOL_SEL(HEAD_RATIO_ONE, 0),
                         ASCENDC_TPL_BOOL_SEL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_SEL(IS_VEC_S2PHYADDR, 0)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
                         ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_PA_BBND),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, CSA_TEMPLATE),
                         ASCENDC_TPL_BOOL_SEL(SPLIT_G, 0, 1), ASCENDC_TPL_BOOL_SEL(HEAD_RATIO_ONE, 0),
                         ASCENDC_TPL_BOOL_SEL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_SEL(IS_VEC_S2PHYADDR, 0, 1)));
#else
// A2/A3: keep the CSA single-head kernel; never compile A5-only flags.
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
                         ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_PA_BBND),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, SWA_TEMPLATE),
                         ASCENDC_TPL_BOOL_SEL(SPLIT_G, 0), ASCENDC_TPL_BOOL_SEL(HEAD_RATIO_ONE, 0),
                         ASCENDC_TPL_BOOL_SEL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_SEL(IS_VEC_S2PHYADDR, 0)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_BOOL_SEL(FLASH_DECODE, 0),
                         ASCENDC_TPL_UINT_SEL(LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_TND),
                         ASCENDC_TPL_UINT_SEL(KV_LAYOUT_T, ASCENDC_TPL_UI_LIST, SMLA_LAYOUT_PA_BBND),
                         ASCENDC_TPL_UINT_SEL(TEMPLATE_MODE, ASCENDC_TPL_UI_LIST, CSA_TEMPLATE),
                         ASCENDC_TPL_BOOL_SEL(SPLIT_G, 0), ASCENDC_TPL_BOOL_SEL(HEAD_RATIO_ONE, 0, 1),
                         ASCENDC_TPL_BOOL_SEL(BATCH_CONSISTENCY, 0, 1), ASCENDC_TPL_BOOL_SEL(IS_VEC_S2PHYADDR, 0)));
#endif

#endif // TEMPLATE_TILING_KEY
