e2e-singlecard-light:
- name: tests/e2e/pull_request/light/one_card/test_qwen3_0_6b.py::test_dense_default_full_and_piecewise_graph
  estimated_time: 226
- name: tests/e2e/pull_request/light/one_card/test_qwen3_embedding_0_6b.py::test_embedding_full_decode_only
  estimated_time: 170
- name: tests/e2e/pull_request/light/one_card/test_qwen3_5_0_8b.py::test_mamba_ssm_multimodal_reasoning_mtp_full_decode_only
  estimated_time: 352
- name: tests/e2e/pull_request/light/one_card/test_qwen3_8b_w8a8.py::test_dense_w8a8_eagle3_full_graph
  estimated_time: 363
e2e-2card-light:
- name: tests/e2e/pull_request/light/two_card/test_qwen3_30b_a3b.py::test_moe_tp_ep_eplb_full_decode_only
  estimated_time: 209
- name: tests/e2e/pull_request/light/two_card/test_qwen3_vl_30b_a3b_instruct.py::test_multimodal_reasoning_pp_full_decode_only
  estimated_time: 268
- name: tests/e2e/pull_request/light/two_card/test_deepseek_multistream_moe.py::test_deepseek_multistream_moe_tp2
  estimated_time: 118
e2e-4card-light:
- name: tests/e2e/pull_request/light/four_card/test_deepseek_v3_2_w8a8_pruning.py::test_moe_w8a8_tp_pp_ep_full_decode_only
  estimated_time: 208
- name: tests/e2e/pull_request/light/four_card/test_deepseek_v3_2_w8a8_pruning.py::test_pd_disaggregation_w8a8_sfa_dsa_full_decode_only
  estimated_time: 157
e2e-singlecard:
- name: tests/e2e/pull_request/full/one_card/compile/test_graphex_norm_quant_fusion.py
  estimated_time: 67
- name: tests/e2e/pull_request/full/one_card/compile/test_graphex_qknorm_rope_fusion.py
  estimated_time: 60
- name: tests/e2e/pull_request/full/one_card/test_auto_fit_max_mode_len.py
  estimated_time: 51
- name: tests/e2e/pull_request/full/one_card/test_eager_mode_acc.py
  estimated_time: 519
- name: tests/e2e/pull_request/full/one_card/test_aclgraph_accuracy.py
  estimated_time: 1850
- name: tests/e2e/pull_request/full/one_card/test_aclgraph_batch_invariant.py
  estimated_time: 517
- name: tests/e2e/pull_request/full/one_card/test_aclgraph_mem.py
  estimated_time: 198
- name: tests/e2e/pull_request/full/one_card/test_async_scheduling.py
  estimated_time: 234
- name: tests/e2e/pull_request/full/one_card/test_batch_invariant.py
  estimated_time: 561
- name: tests/e2e/pull_request/full/one_card/test_camem.py
  estimated_time: 119
- name: tests/e2e/pull_request/full/one_card/test_completion_with_prompt_embeds.py
  estimated_time: 126
- name: tests/e2e/pull_request/full/one_card/test_cpu_offloading.py
  estimated_time: 25
- name: tests/e2e/pull_request/full/one_card/test_guided_decoding.py
  estimated_time: 846
- name: tests/e2e/pull_request/full/one_card/test_ilama_lora.py
  estimated_time: 123
- name: tests/e2e/pull_request/full/one_card/test_llama32_lora.py
  estimated_time: 320
- name: tests/e2e/pull_request/full/one_card/test_qwen3_multi_loras.py
  estimated_time: 106
- name: tests/e2e/pull_request/full/one_card/test_qwen35_densemodel_lora.py
  estimated_time: 292
- name: tests/e2e/pull_request/full/one_card/test_models.py
  estimated_time: 351
- name: tests/e2e/pull_request/full/one_card/test_multistream_overlap_shared_expert.py
  estimated_time: 284
- name: tests/e2e/pull_request/full/one_card/test_sampler.py
  estimated_time: 275
- name: tests/e2e/pull_request/full/one_card/test_vlm.py
  estimated_time: 596
- name: tests/e2e/pull_request/full/one_card/test_multi_instance.py
  estimated_time: 121
- name: tests/e2e/pull_request/full/one_card/test_xlite.py
  estimated_time: 138
- name: tests/e2e/pull_request/full/one_card/compile/test_norm_quant_fusion.py
  estimated_time: 102
- name: tests/e2e/pull_request/full/one_card/pooling/test_classification.py
  estimated_time: 192
- name: tests/e2e/pull_request/full/one_card/pooling/test_embedding.py
  estimated_time: 428
- name: tests/e2e/pull_request/full/one_card/pooling/test_scoring.py
  estimated_time: 605
- name: tests/e2e/pull_request/full/one_card/pooling/test_qwen3_reranker_lora.py
  estimated_time: 318
- name: tests/e2e/pull_request/full/one_card/spec_decode/test_mtp_eagle_correctness.py
  estimated_time: 190
- name: tests/e2e/pull_request/full/one_card/spec_decode/test_v1_spec_decode.py
  estimated_time: 1202
- name: tests/e2e/pull_request/full/one_card/model_runner_v2/test_basic.py
  estimated_time: 26
- name: tests/e2e/pull_request/full/one_card/spec_decode/test_extract_hidden_states.py
  estimated_time: 243
e2e-multicard-2-cards:
- name: tests/e2e/pull_request/full/two_cards/test_aclgraph_capture_replay.py
  estimated_time: 0
  is_skipped: true
- name: tests/e2e/pull_request/full/two_cards/spec_decode/test_spec_decode.py
  estimated_time: 114
- name: tests/e2e/pull_request/full/two_cards/test_offline_weight_load.py
  estimated_time: 0
  is_skipped: true
- name: tests/e2e/pull_request/full/two_cards/test_shared_expert_dp.py
  estimated_time: 0
  is_skipped: true
- name: tests/e2e/pull_request/full/two_cards/test_qwen3_performance.py
  estimated_time: 201
- name: tests/e2e/pull_request/full/two_cards/test_data_parallel.py
  estimated_time: 422
- name: tests/e2e/pull_request/full/two_cards/test_external_launcher.py
  estimated_time: 484
- name: tests/e2e/pull_request/full/two_cards/test_full_graph_mode.py
  estimated_time: 538
- name: tests/e2e/pull_request/full/two_cards/test_ilama_lora_tp2.py
  estimated_time: 100
- name: tests/e2e/pull_request/full/two_cards/test_llama32_lora_tp2.py
  estimated_time: 437
- name: tests/e2e/pull_request/full/two_cards/test_offline_inference_distributed.py::test_qwen3_moe_sp_tp2
  estimated_time: 138
- name: tests/e2e/pull_request/full/two_cards/test_offline_inference_distributed.py::test_qwen3_moe_fc2_tp2
  estimated_time: 117
- name: tests/e2e/pull_request/full/two_cards/test_offline_inference_distributed.py::test_deepseek_v2_lite_fc1_tp2
  estimated_time: 126
- name: tests/e2e/pull_request/full/two_cards/test_offline_inference_distributed.py::test_qwen3_dense_fc1_tp2
  estimated_time: 114
- name: tests/e2e/pull_request/full/two_cards/test_offline_inference_distributed.py::test_qwen3_dense_prefetch_mlp_weight_tp2
  estimated_time: 106
- name: tests/e2e/pull_request/full/two_cards/test_offline_inference_distributed.py::test_deepseek3_2_w8a8_pruning_mtp_tp2_ep
  estimated_time: 172
- name: tests/e2e/pull_request/full/two_cards/test_offline_inference_distributed.py::test_deepseek3_2_w8a8c8_pruning_mtp_tp2_ep
  estimated_time: 167
- name: tests/e2e/pull_request/full/two_cards/test_prefix_caching.py
  estimated_time: 406
- name: tests/e2e/pull_request/full/two_cards/test_qwen3_moe.py
  estimated_time: 582
- name: tests/e2e/pull_request/full/two_cards/test_qwen3_moe_routing_replay.py
  estimated_time: 192
- name: tests/e2e/pull_request/full/two_cards/test_single_request_aclgraph.py
  estimated_time: 287
- name: tests/e2e/pull_request/full/two_cards/test_disaggregated_encoder.py
  estimated_time: 164
- name: tests/e2e/pull_request/full/two_cards/test_sp_pass.py
  estimated_time: 217
- name: tests/e2e/pull_request/full/two_cards/test_sequence_parallelism_moe.py
  estimated_time: 44
e2e-multicard-4-cards:
- name: tests/e2e/pull_request/full/four_cards/test_qwen3_next.py
  estimated_time: 1725
- name: tests/e2e/pull_request/full/four_cards/test_qwen3_5.py
  estimated_time: 824
- name: tests/e2e/pull_request/full/four_cards/test_data_parallel_tp2.py
  estimated_time: 289
- name: tests/e2e/pull_request/full/four_cards/test_kimi_k2.py
  estimated_time: 18
- name: tests/e2e/pull_request/full/four_cards/test_deepseek_v4.py
  estimated_time: 600
- name: tests/e2e/multicard/4-cards/long_sequence/test_accuracy.py
  estimated_time: 2541
- name: tests/e2e/pull_request/full/four_cards/long_sequence/test_basic.py
  estimated_time: 2482
- name: tests/e2e/pull_request/full/four_cards/long_sequence/test_chunked_prefill_cp.py
  estimated_time: 1132
- name: tests/e2e/pull_request/full/four_cards/long_sequence/test_prefix_caching_cp.py
  estimated_time: 1043
- name: tests/e2e/pull_request/full/four_cards/long_sequence/test_mtp.py
  estimated_time: 60
  is_skipped: true
- name: tests/e2e/pull_request/full/four_cards/spec_decode/test_mtp_qwen3_next.py
  estimated_time: 310
- name: tests/e2e/pull_request/full/four_cards/test_pipeline_parallel.py
  estimated_time: 505
- name: tests/e2e/pull_request/full/four_cards/test_profiling_chunk_performance.py
  estimated_time: 134
