#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
#
name: E2E-Full

on:
  pull_request:
    branches:
      - 'main'
      - '*-dev'
      - 'releases/v*'
    types: [ labeled, synchronize ]

# Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly
# declared as "shell: bash -el {0}" on steps that need to be properly activated.
# It's used to activate ascend-toolkit environment variables.
defaults:
  run:
    shell: bash -el {0}

permissions:
  contents: read
  pull-requests: write
  issues: write

# only cancel in-progress runs of the same workflow
# and ignore the lint / 1 card / 4 cards test type
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: linux-aarch64-a2b3-0
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ready') && contains(github.event.pull_request.labels.*.name, 'ready-for-test') }}
    outputs:
      e2e_tracker: ${{ steps.filter.outputs.e2e_tracker }}
      ut_tracker: ${{ steps.filter.outputs.ut_tracker }}
    steps:
      - name: Setup git proxy
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global url."https://gh-proxy.test.osinfra.cn/https://github.com/".insteadOf https://github.com/
      # NOTE: Do not update the version of checkout, there have some issue on self_hosted runner with the higher version
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            e2e_tracker:
              - '.github/workflows/pr_test_full.yaml'
              - '.github/workflows/_e2e_test.yaml'
              - 'vllm_ascend/**'
              - 'csrc/**'
              - 'cmake/**'
              - 'tests/e2e/**'
              - 'CMakeLists.txt'
              - 'setup.py'
              - 'requirements.txt'
              - 'requirements-dev.txt'
              - 'requirements-lint.txt'
              - 'packages.txt'
            ut_tracker:
              - 'tests/ut/**'

  e2e-test:
    name: e2e-full
    strategy:
      matrix:
        vllm_version: [5af684c31912232e5c89484c2e8259e0fac6c55b, v0.19.0]
    needs: [changes]
    if: ${{ needs.changes.outputs.e2e_tracker == 'true' || needs.changes.outputs.e2e_tracker == true }}
    uses: ./.github/workflows/_e2e_test.yaml
    with:
      vllm: ${{ matrix.vllm_version }}
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.5.1-910b-ubuntu22.04-py3.11
      contains_310: false
      type: full
    secrets:
      HW_OBS_AK: ${{ secrets.HW_OBS_AK }}
      HW_OBS_SK: ${{ secrets.HW_OBS_SK }}

  parse-trigger:
    name: Parse /e2e comment
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ready') }}
    uses: ./.github/workflows/_parse_trigger.yaml
    with:
      parse_e2e_comment: true

  e2e-comment-test:
    name: e2e-comment (${{ matrix.vllm_version }})
    strategy:
      fail-fast: false
      matrix:
        vllm_version: [v0.19.0]
    needs: [parse-trigger]
    if: ${{ needs.parse-trigger.outputs.allowed == 'true' }}
    uses: ./.github/workflows/_e2e_test.yaml
    with:
      vllm: ${{ matrix.vllm_version }}
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.5.0-910b-ubuntu22.04-py3.11
      type: comment
      ref: ${{ needs.parse-trigger.outputs.pr_sha }}
      singlecard_tests: ${{ needs.parse-trigger.outputs.singlecard_tests }}
      multicard_2_tests: ${{ needs.parse-trigger.outputs.multicard_2_tests }}
      multicard_4_tests: ${{ needs.parse-trigger.outputs.multicard_4_tests }}
      p310_tests: ${{ needs.parse-trigger.outputs.p310_tests }}